if: (branch = master) OR (type = pull_request)
language: csharp
mono: none
dotnet: 3.1

solution: BoringHelpers.sln
script:
  - dotnet restore
  - dotnet test -f netcoreapp2.1
  - dotnet test -f netcoreapp3.1
